version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "automerge"
- package-ecosystem: gitsubmodule
  directory: "/"
  schedule:
    interval: daily
    time: '04:00'
  open-pull-requests-limit: 10
  labels:
    - "dependencies"
    - "automerge"
