name: ios
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: macOS-latest
    timeout-minutes: 30
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: Apple-Actions/import-codesign-certs@v1
      with:
        p12-file-base64: ${{ secrets.CERTIFICATES_P12 }}
        p12-password: ${{ secrets.CERTIFICATES_P12_PASSWORD }}
    - uses: Apple-Actions/download-provisioning-profiles@v1
      with:
        bundle-id: ${{ secrets.APPSTORE_BUNDLE_ID }}
        issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
        api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
        api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
    - run: PRODUCT_NAME=${{ secrets.APPSTORE_PRODUCT_NAME }} DEVELOPMENT_TEAM=${{ secrets.APPSTORE_DEVELOPMENT_TEAM }} PRODUCT_BUNDLE_IDENTIFIER=${{ secrets.APPSTORE_BUNDLE_ID }} make init
    - run: make heaps-world
    - run: make
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ secrets.APPSTORE_PRODUCT_NAME}}.app
        path: build/Release-iphoneos/${{ secrets.APPSTORE_PRODUCT_NAME}}.app
    # need app-store provisioning profile
    # - uses: Apple-Actions/upload-testflight-build@master
    #   with:
    #     app-path: build/Release-iphoneos/*.ipa
    #     issuer-id: ${{ secrets.APPSTORE_ISSUER_ID }}
    #     api-key-id: ${{ secrets.APPSTORE_KEY_ID }}
    #     api-private-key: ${{ secrets.APPSTORE_PRIVATE_KEY }}
